version: '2'
services:
  web:
    build: .
    ports:
    - "3000:3000"
    links:
    - mongo
    volumes:
    - /home/motahare/Desktop/mydata:/usr/src/app/data

  mongo:
    image: mongo
    ports:
    - "27017:27017"
  